-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE Board_Details
(
    Board_ID character varying,
    Region_Name character varying,
    Board_Name character varying,
    Board_Type character varying,
    Board_Language character varying,
    Board_Website character varying,
    PRIMARY KEY (Board_ID)
);

CREATE TABLE School_Details
(
    School_ID character varying,
    School_Name character varying,
    School_Level character varying,
    Board_ID character varying,
    PRIMARY KEY (School_ID)
);

CREATE TABLE Additional_Details
(
    Additional_Details_ID character varying,
    School_Language character varying,
    School_Type character varying,
    School_Special_Conditions character varying,
    Grade_Range character varying,
    School_ID character varying,
    PRIMARY KEY (Additional_Details_ID)
);

CREATE TABLE Address
(
    Address_ID character varying,
    Street character varying,
    City character varying,
    Province character varying,
    Postal_Code character varying,
    School_ID character varying,
    PRIMARY KEY (Address_ID)
);

CREATE TABLE Contact_Details
(
    Contact_Details_ID character varying,
    Phone character varying,
    Fax character varying,
    Email character varying,
    Website character varying,
    School_ID character varying,
    PRIMARY KEY (Contact_Details_ID)
);

ALTER TABLE School_Details
    ADD FOREIGN KEY (Board_ID)
    REFERENCES Board_Details (Board_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE Additional_Details
    ADD FOREIGN KEY (School_ID)
    REFERENCES School_Details (School_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE Address
    ADD FOREIGN KEY (School_ID)
    REFERENCES School_Details (School_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE Contact_Details
    ADD FOREIGN KEY (School_ID)
    REFERENCES School_Details (School_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;